# MAKE SURE THE VALUES BELOW ARE A GOOD REPRESENTATION OF YOUR SERVERS ECONOMY.
# THE DEFAULT BURN RATE IS 0. THIS SHOULD BE SET TO BETWEEN 0 - 99
# Burn Rate = % amount of EMC lost per condense. BURN_RATE: 20 = 20%
auto-update: true
DISABLE_EMC2_WARNING: false
EMC_VALUES:
  BURN_RATE: 0
  BASE:
    GRASS_BLOCK: 1
    DIRT: 1
    PODZOL: 1
    CRIMSON_NYLIUM: 1
    WARPED_NYLIUM: 1
    COBBLESTONE: 1
    DIORITE: 1
    ANDESITE: 1
    GRANITE: 1
    OAK_SAPLING: 2
    SPRUCE_SAPLING: 2
    BIRCH_SAPLING: 2
    JUNGLE_SAPLING: 2
    ACACIA_SAPLING: 2
    DARK_OAK_SAPLING: 2
    SAND: 1
    RED_SAND: 1
    GRAVEL: 1
    GOLD_ORE: 0
    IRON_ORE: 0
    COAL_ORE: 0
    NETHER_GOLD_ORE: 0
    OAK_LOG: 4
    SPRUCE_LOG: 4
    BIRCH_LOG: 4
    JUNGLE_LOG: 4
    ACACIA_LOG: 4
    DARK_OAK_LOG: 4
    CRIMSON_STEM: 4
    WARPED_STEM: 4
    STRIPPED_OAK_LOG: 4
    STRIPPED_SPRUCE_LOG: 4
    STRIPPED_BIRCH_LOG: 4
    STRIPPED_JUNGLE_LOG: 4
    STRIPPED_ACACIA_LOG: 4
    STRIPPED_DARK_OAK_LOG: 4
    STRIPPED_CRIMSON_STEM: 4
    STRIPPED_WARPED_STEM: 4
    STRIPPED_OAK_WOOD: 4
    STRIPPED_SPRUCE_WOOD: 4
    STRIPPED_BIRCH_WOOD: 4
    STRIPPED_JUNGLE_WOOD: 4
    STRIPPED_ACACIA_WOOD: 4
    STRIPPED_DARK_OAK_WOOD: 4
    STRIPPED_CRIMSON_HYPHAE: 4
    STRIPPED_WARPED_HYPHAE: 4
    OAK_WOOD: 4
    SPRUCE_WOOD: 4
    BIRCH_WOOD: 4
    JUNGLE_WOOD: 4
    ACACIA_WOOD: 4
    DARK_OAK_WOOD: 4
    CRIMSON_HYPHAE: 4
    WARPED_HYPHAE: 4
    OAK_LEAVES: 1
    SPRUCE_LEAVES: 1
    BIRCH_LEAVES: 1
    JUNGLE_LEAVES: 1
    ACACIA_LEAVES: 1
    DARK_OAK_LEAVES: 1
    WET_SPONGE: 16
    LAPIS_ORE: 0
    COBWEB: 4
    GRASS: 1
    FERN: 1
    DEAD_BUSH: 1
    SEAGRASS: 1
    SEA_PICKLE: 4
    DANDELION: 2
    POPPY: 2
    BLUE_ORCHID: 2
    ALLIUM: 2
    AZURE_BLUET: 2
    RED_TULIP: 2
    ORANGE_TULIP: 2
    WHITE_TULIP: 2
    PINK_TULIP: 2
    OXEYE_DAISY: 2
    CORNFLOWER: 2
    LILY_OF_THE_VALLEY: 2
    WITHER_ROSE: 32
    BROWN_MUSHROOM: 4
    RED_MUSHROOM: 4
    CRIMSON_FUNGUS: 4
    WARPED_FUNGUS: 4
    CRIMSON_ROOTS: 2
    WARPED_ROOTS: 2
    WEEPING_VINES: 2
    TWISTING_VINES: 2
    SUGAR_CANE: 2
    KELP: 1
    BAMBOO: 1
    OBSIDIAN: 16
    CHORUS_PLANT: 2
    CHORUS_FLOWER: 8
    DIAMOND_ORE: 0
    REDSTONE_ORE: 0
    ICE: 1
    CACTUS: 1
    PUMPKIN: 4
    CARVED_PUMPKIN: 4
    NETHERRACK: 1
    SOUL_SAND: 2
    SOUL_SOIL: 2
    BASALT: 1
    BROWN_MUSHROOM_BLOCK: 4
    RED_MUSHROOM_BLOCK: 4
    MUSHROOM_STEM: 4
    VINE: 2
    MYCELIUM: 8
    LILY_PAD: 8
    END_STONE: 2
    DRAGON_EGG: 16384
    EMERALD_ORE: 0
    NETHER_QUARTZ_ORE: 0
    SUNFLOWER: 2
    LILAC: 2
    ROSE_BUSH: 2
    PEONY: 2
    TALL_GRASS: 1
    LARGE_FERN: 1
    TURTLE_EGG: 64
    DEAD_TUBE_CORAL_BLOCK: 8
    DEAD_BRAIN_CORAL_BLOCK: 8
    DEAD_BUBBLE_CORAL_BLOCK: 8
    DEAD_FIRE_CORAL_BLOCK: 8
    DEAD_HORN_CORAL_BLOCK: 8
    TUBE_CORAL_BLOCK: 8
    BRAIN_CORAL_BLOCK: 8
    BUBBLE_CORAL_BLOCK: 8
    FIRE_CORAL_BLOCK: 8
    HORN_CORAL_BLOCK: 8
    TUBE_CORAL: 8
    BRAIN_CORAL: 8
    BUBBLE_CORAL: 8
    FIRE_CORAL: 8
    HORN_CORAL: 8
    DEAD_TUBE_CORAL: 8
    DEAD_BRAIN_CORAL: 8
    DEAD_BUBBLE_CORAL: 8
    DEAD_FIRE_CORAL: 8
    DEAD_HORN_CORAL: 8
    TUBE_CORAL_FAN: 8
    BRAIN_CORAL_FAN: 8
    BUBBLE_CORAL_FAN: 8
    FIRE_CORAL_FAN: 8
    HORN_CORAL_FAN: 8
    DEAD_TUBE_CORAL_FAN: 8
    DEAD_BRAIN_CORAL_FAN: 8
    DEAD_BUBBLE_CORAL_FAN: 8
    DEAD_FIRE_CORAL_FAN: 8
    DEAD_HORN_CORAL_FAN: 8
    SCUTE: 32
    APPLE: 8
    DIAMOND: 2048
    IRON_INGOT: 64
    GOLD_INGOT: 128
    NETHERITE_SCRAP: 4096
    STRING: 4
    FEATHER: 2
    GUNPOWDER: 8
    WHEAT_SEEDS: 2
    WHEAT: 2
    FLINT: 1
    PORKCHOP: 4
    WATER_BUCKET: 128
    LAVA_BUCKET: 256
    SADDLE: 256
    REDSTONE: 16
    COAL: 16
    SNOWBALL: 2
    MILK_BUCKET: 256
    CLAY_BALL: 8
    SLIME_BALL: 8
    EGG: 4
    GLOWSTONE_DUST: 8
    COD: 64
    SALMON: 64
    TROPICAL_FISH: 128
    PUFFERFISH: 64
    INK_SAC: 16
    COCOA_BEANS: 16
    LAPIS_LAZULI: 16
    BONE: 4
    MELON_SLICE: 2
    BEEF: 4
    CHICKEN: 4
    ROTTEN_FLESH: 4
    ENDER_PEARL: 8
    BLAZE_ROD: 8
    GHAST_TEAR: 16
    NETHER_WART: 8
    SPIDER_EYE: 4
    EMERALD: 128
    CARROT: 2
    POTATO: 2
    POISONOUS_POTATO: 8
    SKELETON_SKULL: 128
    WITHER_SKELETON_SKULL: 128
    ZOMBIE_HEAD: 128
    CREEPER_HEAD: 128
    DRAGON_HEAD: 1024
    NETHER_STAR: 1024
    QUARTZ: 32
    PRISMARINE_SHARD: 8
    PRISMARINE_CRYSTALS: 16
    RABBIT: 2
    RABBIT_FOOT: 16
    RABBIT_HIDE: 2
    NAME_TAG: 256
    MUTTON: 2
    CHORUS_FRUIT: 4
    BEETROOT: 2
    BEETROOT_SEEDS: 2
    DRAGON_BREATH: 512
    ELYTRA: 0
    SHULKER_SHELL: 32
    TRIDENT: 512
    PHANTOM_MEMBRANE: 16
    NAUTILUS_SHELL: 128
    HEART_OF_THE_SEA: 8192
    BELL: 128
    SWEET_BERRIES: 2
    SHROOMLIGHT: 4
    HONEYCOMB: 1
    CRYING_OBSIDIAN: 64
    BLACKSTONE: 2
    GILDED_BLACKSTONE: 16
    HONEY_BOTTLE: 1
    PLAYER_HEAD: 0
    RAW_IRON: 32
    RAW_GOLD: 64
    RAW_COPPER: 16
    COPPER_INGOT: 32
  SLIMEFUN:
    COPPER_DUST: 32
    IRON_DUST: 32
    GOLD_DUST: 64
    TIN_DUST: 32
    MAGNESIUM_DUST: 32
    ZINC_DUST: 32
    LEAD_DUST: 32
    SILVER_DUST: 32
    ALUMINUM_DUST: 32
    NETHER_ICE: 128
    BUCKET_OF_OIL: 0
    SIFTED_ORE: 0
    BASIC_CIRCUIT_BOARD: 1024
MESSAGES:
  COMMAND_SUBCOMMAND: "請選擇一個有效的子指令"
  COMMAND_SELECT_ITEM: "請選擇一種物品類型"
  COMMAND_EMC_ITEM_MUST_HOLD: "你必須拿著一個物品才能看到它的EMC值"
  COMMAND_EMC_NONE: "這個物品並不能濃縮為EMC"
  COMMAND_ITEM_GIVEN: "你已被給予 {0}"
  GENERAL_NO_INVENTORY_SPACE: "你沒有足夠的空間來存放此物品"
  EVENT_CANT_OPEN_NOT_OWNER: "你不能打開其他玩家所擁有的EMC方塊."
  EVENT_PLACE_EMC_CHEST_ADJACENT: "你不能放置EMC箱子在另一個箱子旁."
  EVENT_CHEST_ITEM_SET: "將物品合成設置為你手持的物品."
  EVENT_CHEST_ITEM_UNSET: "物品合成已停止."
ITEMS:
  GENERAL_CRAFTING_ITEM: "製作原料"
  TRANSMUTATION_ORB_NAME: "煉金球"
  TRANSMUTATION_ORB_LORE:
    - "一個強大的魔法神器,"
    - "可以讓你將各種物品"
    - "凝聚成EMC."
    - "EMC可以通過一個簡單的"
    - "煉金過程轉變成其他物品"
  TRANSMUTATION_ORB_INFO: "右鍵打開"
  ALCHEMICAL_COAL_NAME: "煉金術煤炭"
  MOBIUS_FUEL_NAME: "莫比烏斯燃料"
  AETERNALIS_FUEL_NAME: "永恆燃料"
  DARK_MATTER_NAME: "暗物質"
  RED_MATTER_NAME: "紅物質"
  DISSOLUTION_CHEST_NAME: "溶解箱"
  DISSOLUTION_CHEST_LORE:
    - "這個箱子可以將其內容物"
    - "分解成EMC, 然後添加到"
    - "放置者的EMC池中."
  CONDENSATOR_CHEST_NAME: "凝聚箱"
  CONDENSATOR_CHEST_LORE:
    - "這個箱子可以從放置者的EMC池中"
    - "將EMC凝聚回具有同等價值的物品."
    - ""
    - "以這種方式合成的物品將"
    - "需要使用多50%的EMC."
  CONDENSATOR_CHEST_SET_ITEM: "蹲下 + 右鍵 這個箱子來設置手持的物品."
GUI:
  SLOT_BORDER_NAME: "等價技術"
  SLOT_FILLER_NAME: "沒有配方在這"
  ORB_ITEM_ADDED: "你已學會如何合成一個新物品!"
  EMC_ITEM_WITHDRAW_ONE: "合成 1個"
  EMC_ITEM_WITHDRAW_STACK: "合成 1組"
  EMC_INFO_NAME: "EMC知識"
  EMC_INFO_LORE_RECIPES: "EMC物品已解鎖"
  EMC_NOT_ENOUGH: "沒有足夠的EMC"
  EMC_ITEM_META: "只能能濃縮普通物品 (沒有附魔, 名稱 等等...)"
DEBUG:
  SHOW_DEBUGGING_LOGS: false