name: EquivalencyTech
version: ${project.version}
description: 黏液科技附加 等價技術 繁體翻譯版.
main: io.github.sefiraat.equivalencytech.EquivalencyTech
api-version: 1.16
softdepend:
  - Slimefun
permissions:
  equitech.admin:
    description: Allows access to /et
  equitech.bypass:
    description: Can open/interact with EMC objects owned by other players